# Generated by Django 3.0.7 on 2020-06-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imienne',
            fields=[
                ('id_biletu', models.AutoField(primary_key=True, serialize=False)),
                ('data_aktywacji', models.DateTimeField(blank=True, null=True)),
                ('data_waznosci', models.DateTimeField(blank=True, null=True)),
                ('id_transakcji', models.IntegerField()),
                ('id_nosnika', models.IntegerField(blank=True, null=True)),
                ('id_ulgi', models.IntegerField(blank=True, null=True)),
                ('id_typu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Imienne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodyPlatnosci',
            fields=[
                ('id_metody_platnosci', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Metody_platnosci',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MiejscaTransakcji',
            fields=[
                ('id_miejsca_transakcji', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('miasto', models.CharField(blank=True, max_length=30, null=True)),
                ('ulica', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Miejsca_transakcji',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nieimienne',
            fields=[
                ('id_biletu', models.AutoField(primary_key=True, serialize=False)),
                ('data_aktywacji', models.DateTimeField(blank=True, null=True)),
                ('data_waznosci', models.DateTimeField(blank=True, null=True)),
                ('id_transakcji', models.IntegerField()),
                ('id_typu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Nieimienne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NosnikiElektroniczne',
            fields=[
                ('id_nosnika', models.AutoField(primary_key=True, serialize=False)),
                ('data_waznosci', models.DateTimeField()),
                ('id_ulgi', models.IntegerField()),
            ],
            options={
                'db_table': 'Nosniki_elektroniczne',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NosnikiKartonikowe',
            fields=[
                ('id_nosnika', models.AutoField(primary_key=True, serialize=False)),
                ('kod', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Nosniki_kartonikowe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pasazerowie',
            fields=[
                ('id_pasazera', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Pasazerowie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transakcje',
            fields=[
                ('id_transakcji', models.AutoField(primary_key=True, serialize=False)),
                ('data_zakupu', models.DateTimeField()),
                ('kwota', models.FloatField()),
            ],
            options={
                'db_table': 'Transakcje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypyBiletow',
            fields=[
                ('id_typu_biletu', models.AutoField(primary_key=True, serialize=False)),
                ('cena', models.FloatField()),
                ('strefa', models.CharField(max_length=3)),
                ('czas_waznosci', models.DurationField()),
            ],
            options={
                'db_table': 'Typy_biletow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypyNosnikow',
            fields=[
                ('id_typu_nosnika', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Typy_nosnikow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypyUlgi',
            fields=[
                ('id_typu_ulgi', models.AutoField(primary_key=True, serialize=False)),
                ('kod_podstawowy', models.IntegerField()),
                ('wielkosc_ulgi', models.IntegerField()),
                ('nazwa', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Typy_ulgi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ulgi',
            fields=[
                ('id_ulgi', models.AutoField(primary_key=True, serialize=False)),
                ('data_waznosci', models.DateField()),
            ],
            options={
                'db_table': 'Ulgi',
                'managed': False,
            },
        ),
    ]
